language: php
php:
  - '7.0'
services:
  - mysql
install:
  - sudo apt update -qq
  - sudo apt install -y apache2 libapache2-mod-fastcgi
  - sudo rm -rf /var/www/html/hashtopolis
  - sudo git clone https://github.com/s3inlc/hashtopolis /var/www/html/hashtopolis
  - sudo /bin/bash ci/files/prepare.sh
  - php -f ci/server/setup.php $TRAVIS_BRANCH
  - sudo cp -f ci/files/apache.conf /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

script:
  - php -f ci/run.php master