language: php
php:
  - '7.0'
services:
  - mysql
install:
  - sudo apt update -qq
  - sudo apt install -y apache2 libapache2-mod-fastcgi
  - sudo cp -f ci/files/apache.conf /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

script:
  - php -f ci/server/setup.php $TRAVIS_BRANCH
  - sudo chown -R www-data ci/env
  - php -f ci/run.php master