dist: bionic
language: php
os: linux
php:
  - "8.0"
  - "7.4"
  - "7.2"

services:
  - mysql
install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt update -qq
  - sudo apt install -qq -y apache2 libapache2-mod-php${TRAVIS_PHP_VERSION:0:3} php${TRAVIS_PHP_VERSION:0:3}-cli php${TRAVIS_PHP_VERSION:0:3}-common php${TRAVIS_PHP_VERSION:0:3}-json php${TRAVIS_PHP_VERSION:0:3}-opcache php${TRAVIS_PHP_VERSION:0:3}-xml php${TRAVIS_PHP_VERSION:0:3}-readline php-pear php${TRAVIS_PHP_VERSION:0:3}-curl php${TRAVIS_PHP_VERSION:0:3}-mysql php${TRAVIS_PHP_VERSION:0:3}
  - sudo cp -f ci/files/apache.conf /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - php -v
  - sudo rm -rf /var/www/html/hashtopolis
  - sudo git clone https://github.com/hashtopolis/server /var/www/html/hashtopolis
  - sudo /bin/bash ci/files/prepare.sh $TRAVIS_BRANCH
  - sudo php -f ci/server/setup.php $TRAVIS_BRANCH

env:
  - VERSION="master"
  - VERSION="0.12.0"
  - VERSION="0.11.0"
  - VERSION="0.10.0"

jobs:
  # older versions only tested for master and PRs
  exclude:
    - if: (branch != master AND type != pull_request)
      php: "7.1"
    - if: (branch != master AND type != pull_request)
      php: "7.0"
    - if: (branch != master AND type != pull_request)
      php: "5.6"
    - if: (branch != master AND type != pull_request)
      env: VERSION="0.11.0"
    - if: (branch != master AND type != pull_request)
      env: VERSION="0.10.0"


script:
  - php -f ci/run.php master $VERSION
